// <auto-generated />
using System;
using CS395SI_Spring2023_Group1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS395SI_Spring2023_Group1.Migrations
{
    [DbContext(typeof(CS395SI_Spring2023_Group1Context))]
    [Migration("20250210031758_AddStudentID")]
    partial class AddStudentID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2023_Group1_Profile_Sys", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerPhoneNum1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerPhoneNum2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerPhoneNum3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerRelation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerRelation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("HSGrad")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("LicenseClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LicenseExp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Talents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USCitizen")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Under18")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Email");

                    b.ToTable("Spring2023_Group1_Profile_Sys");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2023_Group1_Schedules", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.Property<string>("ServiceID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleID");

                    b.ToTable("Spring2023_Group1_Schedules");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2023_Group1_Scheduling_Form", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsOnFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSaturday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSunday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnWednesday")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestID");

                    b.ToTable("Spring2023_Group1_Scheduling_Form");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2023_Group1_Services", b =>
                {
                    b.Property<string>("ServiceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceHours")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Spring2023_Group1_Services");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2024_Group2_Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SectionID")
                        .HasColumnType("int");

                    b.Property<string>("ServiceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleID");

                    b.ToTable("Spring2024_Group2_Schedule");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2024_Group2_Sections", b =>
                {
                    b.Property<int>("sectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sectionID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("endTime")
                        .HasColumnType("time");

                    b.Property<string>("serviceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("startTime")
                        .HasColumnType("time");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weekDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sectionID");

                    b.ToTable("Spring2024_Group2_Sections");
                });

            modelBuilder.Entity("CS395SI_Spring2023_K4S.Model.Spring2024_Group2_Session", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionID");

                    b.ToTable("Spring2024_Group2_Session");
                });
#pragma warning restore 612, 618
        }
    }
}
